server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: http://localhost:8086
          predicates:
            - Path=/post/*
          filters:
            - BasicAuthGatewayFilter
